import React from 'react';
import ModulePage from '../src/components/custom/ModulePage';
import Storage from '../public/icons/databaseLg.svg';
import Query from '../public/icons/query.svg';
import Tick from '../public/icons/tick.svg';
import Schema from '../public/moduleIcons/Schema.svg';
import SchemaData from '../public/moduleIcons/schemaData.svg';
import CustomEndpoint from '../public/moduleIcons/customEndpoint.svg';
import DatabaseIcon from '../public/icons/database.svg';
import { NextSeo } from 'next-seo';

const Database = () => {
  const SEO = {
    title: 'Database',
    description: 'Database Module',
    openGraph: {
      title: 'Database',
      description: 'Database Module',
      article: {
        tags: ['database', 'mongoDB', 'PostgreSQL', 'query'],
      },
    },
  };
  return (
    <>
      <NextSeo {...SEO} />
      <ModulePage
        moduleName="Database"
        title="The glue between the database engine and Conduit. It provides an Object–relational mapping (ORM)  for converting data between incompatible type systems using object-oriented programming languages. This module facilitates the management of content types through the generation of db level schemas, the creation and manipulation of schema document entries and the registration of fine-tuned custom endpoints. Content is delivered through REST and GraphQL."
        docsLink="/docs/modules/database"
        img={<Storage />}
        features={[
          {
            title: 'Supports MongoDB and PostgreSQL',
            description: 'You can have either a document based or a relational database, options!',
            url: '/docs/modules/database/get-started#prerequisites',
            icon: <DatabaseIcon />,
          },
          {
            title: 'Query your data ',
            description:
              'Without the need of writing complex SQL queries. Schemas can be manipulated through model controller objects automatically generated by the module itself.',
            url: '/docs/modules/database/queries',
            icon: <Query />,
          },
          {
            title: 'Introspection',
            description:
              'Already have an existing project? Conduit allows you to import your data and continue right where you left off!',
            url: '/docs/modules/database/introspection',
            icon: <Tick />,
          },
          {
            title: 'Schemas',
            description:
              'Create any content type (schema). Schemas can contain fields of different types.',
            url: '/docs/modules/cms/get-started#schemas-example',
            icon: <Schema />,
          },
          {
            title: 'Schema data',
            description:
              'Create custom content types based on schemas! You can register individual entries in a schema to store your data.',
            url: '/docs/modules/cms/get-started#documents-example',
            icon: <SchemaData />,
          },
          {
            title: 'Custom endpoints',
            description:
              'Create powerful custom endpoints, with pagination, sorting, population, authentication and more!',
            url: '/docs/modules/cms/get-started#custom-endpoints-example',
            icon: <CustomEndpoint />,
          },
        ]}
      />
    </>
  );
};

export default Database;
