[[redirects]]
from = "/docs"
to = "/docs/overview/intro"
status = 200
force = true
[[redirects]]
from = "/docs/"
to = "/docs/overview/intro"
status = 200
force = true
[[redirects]]
from = "/docs/*"
to = "/:splat"
status = 200
force = true
