on:
  pull_request:
    types:
      - opened
    paths:
      - "documentation/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: yarn
      - run: cd documentation && yarn build
