name: Docs (archive site)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "documentation/**"
      - ".github/workflows/docs.test.yaml"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"
          cache-dependency-path: documentation/yarn.lock
      - name: Install
        run: yarn install --frozen-lockfile
        working-directory: documentation
      - name: Build Docusaurus archive
        run: yarn build
        working-directory: documentation
