on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "www/**"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - run: cd www && npm install
      - run: yarn build
